//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACUManager.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WSACUSoap")]
    public interface WSACUSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UserQuery(string workingTag, string userId, string userName, string passWord);
        
        // CODEGEN: Parameter 'avatar' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ACUManager.ServiceReference1.UserSaveResponse UserSave(ACUManager.ServiceReference1.UserSaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupUserQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupUserQuery(string workingTag, string groupId, string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupUserSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupUserSave(string workingTag, string groupId, string groupName, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupUserDetailQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupUserDetailQuery(string workingTag, string groupUserId, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupUserDetailSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupUserDetailSave(string workingTag, string groupUserId, string userId, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CardQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CardQuery(string workingTag, string cardId, string cardNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CardSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CardSave(string workingTag, string cardId, string cardNo, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CardDetailQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CardDetailQuery(string workingTag, string userId, string cardNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CardDetailSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CardDetailSave(string workingTag, string cardNo, string userId, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupAccessQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupAccessQuery(string workingTag, string groupId, string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupAccessSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupAccessSave(string workingTag, string groupId, string groupName, string groupDescription, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupAccessUQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupAccessUQuery(string workingTag, string groupId, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupAccessUSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupAccessUSave(string workingTag, string groupAccessId, string userId, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupAccessLQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupAccessLQuery(string workingTag, string groupId, string accessLevelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupAccessLSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupAccessLSave(string workingTag, string groupAccessId, string accessLevelId, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupAccessUGQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupAccessUGQuery(string workingTag, string groupId, string userGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupAccessUGSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupAccessUGSave(string workingTag, string groupAccessId, string userGroupId, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLevelQry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AccessLevelQry(string workingTag, string accessLevelID, string accessLevelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLevelSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AccessLevelSave(string workingTag, string accessLevelID, string accessLevelName, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLevelDQry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AccessLevelDQry(string workingTag, string accessLevelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLevelDSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AccessLevelDSave(string workingTag, string accessLevelID, string doorID, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLevelSQry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AccessLevelSQry(string workingTag, string accessLevelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLevelSSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AccessLevelSSave(string workingTag, string accessLevelID, string scheduleID, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoorQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DoorQuery(string workingTag, string doorId, string doorName, string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoorSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DoorSave(string workingTag, string doorId, string doorName, string deviceId, string readerNumber, string inputNumber, string outputNumber, string relayNumber, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupDoorQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupDoorQuery(string workingTag, string groupName, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupDoorSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GroupDoorSave(string workingTag, string groupId, string groupName, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScheduleQry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ScheduleQry(string workingTag, string scheduleId, string scheduleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScheduleSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ScheduleSave(string workingTag, string scheduleId, string scheduleName, string description, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeriodQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PeriodQuery(string workingTag, string scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeriodSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PeriodSave(string workingTag, string ScheduleId, string DayInWeek, System.DateTime StartTime, System.DateTime EndTime, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeviceQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DeviceQuery(string workingTag, string deviceId, string deviceName, string deviceIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeviceSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DeviceSave(string workingTag, string deviceId, string deviceName, string deviceIP, string Person, System.DateTime mDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EventQry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EventQry(string workingTag, string eventId, string cardNo, string sDate, string eDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EventSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EventSave(string workingTag, string eventId, System.DateTime eventDate, string device, string functionCode, string cardNo, string doorId, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OperatorQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OperatorQuery(string workingTag, string optLevelid, string optLevelName, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DaysInWeekQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DaysInWeekQuery(string workingTag, string groupId, string groupName, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AttendanceQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AttendanceQuery(string workingTag, System.DateTime attendanceDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LoginQuery(string workingTag, System.DateTime fromDate, System.DateTime toDate);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSave", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserSaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string workingTag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string optLevel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string personName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] avatar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string phoneNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public bool status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public System.DateTime experiedDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public System.DateTime mDate;
        
        public UserSaveRequest() {
        }
        
        public UserSaveRequest(string workingTag, string userId, string optLevel, string userName, string password, string personName, byte[] avatar, string email, string phoneNo, bool status, System.DateTime startDate, System.DateTime experiedDate, string person, System.DateTime mDate) {
            this.workingTag = workingTag;
            this.userId = userId;
            this.optLevel = optLevel;
            this.userName = userName;
            this.password = password;
            this.personName = personName;
            this.avatar = avatar;
            this.email = email;
            this.phoneNo = phoneNo;
            this.status = status;
            this.startDate = startDate;
            this.experiedDate = experiedDate;
            this.person = person;
            this.mDate = mDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSaveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserSaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet UserSaveResult;
        
        public UserSaveResponse() {
        }
        
        public UserSaveResponse(System.Data.DataSet UserSaveResult) {
            this.UserSaveResult = UserSaveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSACUSoapChannel : ACUManager.ServiceReference1.WSACUSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSACUSoapClient : System.ServiceModel.ClientBase<ACUManager.ServiceReference1.WSACUSoap>, ACUManager.ServiceReference1.WSACUSoap {
        
        public WSACUSoapClient() {
        }
        
        public WSACUSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSACUSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSACUSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSACUSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet UserQuery(string workingTag, string userId, string userName, string passWord) {
            return base.Channel.UserQuery(workingTag, userId, userName, passWord);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ACUManager.ServiceReference1.UserSaveResponse ACUManager.ServiceReference1.WSACUSoap.UserSave(ACUManager.ServiceReference1.UserSaveRequest request) {
            return base.Channel.UserSave(request);
        }
        
        public System.Data.DataSet UserSave(string workingTag, string userId, string optLevel, string userName, string password, string personName, byte[] avatar, string email, string phoneNo, bool status, System.DateTime startDate, System.DateTime experiedDate, string person, System.DateTime mDate) {
            ACUManager.ServiceReference1.UserSaveRequest inValue = new ACUManager.ServiceReference1.UserSaveRequest();
            inValue.workingTag = workingTag;
            inValue.userId = userId;
            inValue.optLevel = optLevel;
            inValue.userName = userName;
            inValue.password = password;
            inValue.personName = personName;
            inValue.avatar = avatar;
            inValue.email = email;
            inValue.phoneNo = phoneNo;
            inValue.status = status;
            inValue.startDate = startDate;
            inValue.experiedDate = experiedDate;
            inValue.person = person;
            inValue.mDate = mDate;
            ACUManager.ServiceReference1.UserSaveResponse retVal = ((ACUManager.ServiceReference1.WSACUSoap)(this)).UserSave(inValue);
            return retVal.UserSaveResult;
        }
        
        public System.Data.DataSet GroupUserQuery(string workingTag, string groupId, string groupName) {
            return base.Channel.GroupUserQuery(workingTag, groupId, groupName);
        }
        
        public System.Data.DataSet GroupUserSave(string workingTag, string groupId, string groupName, string Person, System.DateTime mDate) {
            return base.Channel.GroupUserSave(workingTag, groupId, groupName, Person, mDate);
        }
        
        public System.Data.DataSet GroupUserDetailQuery(string workingTag, string groupUserId, string userId) {
            return base.Channel.GroupUserDetailQuery(workingTag, groupUserId, userId);
        }
        
        public System.Data.DataSet GroupUserDetailSave(string workingTag, string groupUserId, string userId, string Person, System.DateTime mDate) {
            return base.Channel.GroupUserDetailSave(workingTag, groupUserId, userId, Person, mDate);
        }
        
        public System.Data.DataSet CardQuery(string workingTag, string cardId, string cardNo) {
            return base.Channel.CardQuery(workingTag, cardId, cardNo);
        }
        
        public System.Data.DataSet CardSave(string workingTag, string cardId, string cardNo, string Person, System.DateTime mDate) {
            return base.Channel.CardSave(workingTag, cardId, cardNo, Person, mDate);
        }
        
        public System.Data.DataSet CardDetailQuery(string workingTag, string userId, string cardNo) {
            return base.Channel.CardDetailQuery(workingTag, userId, cardNo);
        }
        
        public System.Data.DataSet CardDetailSave(string workingTag, string cardNo, string userId, string Person, System.DateTime mDate) {
            return base.Channel.CardDetailSave(workingTag, cardNo, userId, Person, mDate);
        }
        
        public System.Data.DataSet GroupAccessQuery(string workingTag, string groupId, string groupName) {
            return base.Channel.GroupAccessQuery(workingTag, groupId, groupName);
        }
        
        public System.Data.DataSet GroupAccessSave(string workingTag, string groupId, string groupName, string groupDescription, string Person, System.DateTime mDate) {
            return base.Channel.GroupAccessSave(workingTag, groupId, groupName, groupDescription, Person, mDate);
        }
        
        public System.Data.DataSet GroupAccessUQuery(string workingTag, string groupId, string userId) {
            return base.Channel.GroupAccessUQuery(workingTag, groupId, userId);
        }
        
        public System.Data.DataSet GroupAccessUSave(string workingTag, string groupAccessId, string userId, string Person, System.DateTime mDate) {
            return base.Channel.GroupAccessUSave(workingTag, groupAccessId, userId, Person, mDate);
        }
        
        public System.Data.DataSet GroupAccessLQuery(string workingTag, string groupId, string accessLevelId) {
            return base.Channel.GroupAccessLQuery(workingTag, groupId, accessLevelId);
        }
        
        public System.Data.DataSet GroupAccessLSave(string workingTag, string groupAccessId, string accessLevelId, string Person, System.DateTime mDate) {
            return base.Channel.GroupAccessLSave(workingTag, groupAccessId, accessLevelId, Person, mDate);
        }
        
        public System.Data.DataSet GroupAccessUGQuery(string workingTag, string groupId, string userGroupId) {
            return base.Channel.GroupAccessUGQuery(workingTag, groupId, userGroupId);
        }
        
        public System.Data.DataSet GroupAccessUGSave(string workingTag, string groupAccessId, string userGroupId, string Person, System.DateTime mDate) {
            return base.Channel.GroupAccessUGSave(workingTag, groupAccessId, userGroupId, Person, mDate);
        }
        
        public System.Data.DataSet AccessLevelQry(string workingTag, string accessLevelID, string accessLevelName) {
            return base.Channel.AccessLevelQry(workingTag, accessLevelID, accessLevelName);
        }
        
        public System.Data.DataSet AccessLevelSave(string workingTag, string accessLevelID, string accessLevelName, string Person, System.DateTime mDate) {
            return base.Channel.AccessLevelSave(workingTag, accessLevelID, accessLevelName, Person, mDate);
        }
        
        public System.Data.DataSet AccessLevelDQry(string workingTag, string accessLevelID) {
            return base.Channel.AccessLevelDQry(workingTag, accessLevelID);
        }
        
        public System.Data.DataSet AccessLevelDSave(string workingTag, string accessLevelID, string doorID, string Person, System.DateTime mDate) {
            return base.Channel.AccessLevelDSave(workingTag, accessLevelID, doorID, Person, mDate);
        }
        
        public System.Data.DataSet AccessLevelSQry(string workingTag, string accessLevelID) {
            return base.Channel.AccessLevelSQry(workingTag, accessLevelID);
        }
        
        public System.Data.DataSet AccessLevelSSave(string workingTag, string accessLevelID, string scheduleID, string Person, System.DateTime mDate) {
            return base.Channel.AccessLevelSSave(workingTag, accessLevelID, scheduleID, Person, mDate);
        }
        
        public System.Data.DataSet DoorQuery(string workingTag, string doorId, string doorName, string deviceId) {
            return base.Channel.DoorQuery(workingTag, doorId, doorName, deviceId);
        }
        
        public System.Data.DataSet DoorSave(string workingTag, string doorId, string doorName, string deviceId, string readerNumber, string inputNumber, string outputNumber, string relayNumber, string Person, System.DateTime mDate) {
            return base.Channel.DoorSave(workingTag, doorId, doorName, deviceId, readerNumber, inputNumber, outputNumber, relayNumber, Person, mDate);
        }
        
        public System.Data.DataSet GroupDoorQuery(string workingTag, string groupName, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GroupDoorQuery(workingTag, groupName, fromDate, toDate);
        }
        
        public System.Data.DataSet GroupDoorSave(string workingTag, string groupId, string groupName, string Person, System.DateTime mDate) {
            return base.Channel.GroupDoorSave(workingTag, groupId, groupName, Person, mDate);
        }
        
        public System.Data.DataSet ScheduleQry(string workingTag, string scheduleId, string scheduleName) {
            return base.Channel.ScheduleQry(workingTag, scheduleId, scheduleName);
        }
        
        public System.Data.DataSet ScheduleSave(string workingTag, string scheduleId, string scheduleName, string description, string Person, System.DateTime mDate) {
            return base.Channel.ScheduleSave(workingTag, scheduleId, scheduleName, description, Person, mDate);
        }
        
        public System.Data.DataSet PeriodQuery(string workingTag, string scheduleId) {
            return base.Channel.PeriodQuery(workingTag, scheduleId);
        }
        
        public System.Data.DataSet PeriodSave(string workingTag, string ScheduleId, string DayInWeek, System.DateTime StartTime, System.DateTime EndTime, string Person, System.DateTime mDate) {
            return base.Channel.PeriodSave(workingTag, ScheduleId, DayInWeek, StartTime, EndTime, Person, mDate);
        }
        
        public System.Data.DataSet DeviceQuery(string workingTag, string deviceId, string deviceName, string deviceIP) {
            return base.Channel.DeviceQuery(workingTag, deviceId, deviceName, deviceIP);
        }
        
        public System.Data.DataSet DeviceSave(string workingTag, string deviceId, string deviceName, string deviceIP, string Person, System.DateTime mDate) {
            return base.Channel.DeviceSave(workingTag, deviceId, deviceName, deviceIP, Person, mDate);
        }
        
        public System.Data.DataSet EventQry(string workingTag, string eventId, string cardNo, string sDate, string eDate) {
            return base.Channel.EventQry(workingTag, eventId, cardNo, sDate, eDate);
        }
        
        public System.Data.DataSet EventSave(string workingTag, string eventId, System.DateTime eventDate, string device, string functionCode, string cardNo, string doorId, string status) {
            return base.Channel.EventSave(workingTag, eventId, eventDate, device, functionCode, cardNo, doorId, status);
        }
        
        public System.Data.DataSet OperatorQuery(string workingTag, string optLevelid, string optLevelName, string userId) {
            return base.Channel.OperatorQuery(workingTag, optLevelid, optLevelName, userId);
        }
        
        public System.Data.DataSet DaysInWeekQuery(string workingTag, string groupId, string groupName, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.DaysInWeekQuery(workingTag, groupId, groupName, fromDate, toDate);
        }
        
        public System.Data.DataSet AttendanceQuery(string workingTag, System.DateTime attendanceDate) {
            return base.Channel.AttendanceQuery(workingTag, attendanceDate);
        }
        
        public System.Data.DataSet LoginQuery(string workingTag, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.LoginQuery(workingTag, fromDate, toDate);
        }
    }
}
